### ISSUE TITLE
Страничка фильмов

### ISSUE THREAD

**Issue by horba** [horba/film-finity#12]
В рамках задачи:

- [x] внести необходимые изменения в базу данных
- [x] добавить миграции
- [x] добавить сидинг тестовых данных в базу
- [x] реализовать апи точки, которые возвращают необходимую информацию о фильмах для отображения их на фронте
- [x] реализовать странику "Фильмы" и доступ к ней из меню

Фильмы берутся с сервера

В рамках задачи делаем самый просто вывод фильмов:
- без пагинации
- без сортировок
- без фильтров
- без разделов (новинки, часто смотрят и т.д.)
- без переключения вида плитки/таблица
- без кнопок "мне по вкусу", "последнее добавленное", "ждем вместе"

[исходник](https://www.figma.com/file/QGYATYyXIUHW5a0j7dx65s/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%A4%D0%B8%D0%BB%D1%8C%D0%BC%D1%8B?node-id=2659%3A29366[](url))
![image](https://user-images.githubusercontent.com/11043173/82735505-2ee9b480-9d1a-11ea-8185-02011f0f6872.png)

**Comment by YarNik** [comment]
![moviesPage](https://user-images.githubusercontent.com/24220591/84028898-322ba400-a99a-11ea-85cb-a8f5742309c8.jpg)
